<?php
  
  class JSGauge
  {
  	  var $cDOMID;
  	  var $cLabel;
  	  var $value;
  	  var $min;
	  var $max;
	  var $majorTicks;
	  var $minorTicks;
	  var $majorTickLabel;
	  var $greenFrom;
	  var $greenTo;
	  var $yellowFrom;
	  var $yellowTo;
	  var $redFrom;
	  var $redTo;
	  
	  var $unitsLabel;
	  
	  function SetLabel($cLabel)
	  {
		  $this->cLabel=$cLabel;
	  }
	  
	  function SetGreenArc($nStart,$nEnd)
	  {
		  $this->greenFrom=$nStart;
		  $this->greenTo=$nEnd;
	  }
	  function SetYellowArc($nStart,$nEnd)
	  {
		  $this->yellowFrom=$nStart;
		  $this->yellowTo=$nEnd;
	  }
	  function SetRedArc($nStart,$nEnd)
	  {
		  $this->redFrom=$nStart;
		  $this->redTo=$nEnd;
	  }
	  
	  function SetTickLabelON()
	  {
		  $this->majorTickLabel='true';
	  }
	  function SetTickLabelOFF()
	  {
		  $this->majorTickLabel='false';
	  }
	  
	  function SetTicks($nMinor=5,$nMajor=8)
	  {
		  $this->minorTicks=$nMinor;
		  $this->majorTicks=$nMajor;
	  }
	  
	  function SetValue($nValue,$draw=false)
	  {
		  $this->value=$nValue;
		  if ($draw)
		  {
		  	$this->draw();  
		  }
	  }
	  
	  function SetScaleRange($nMin=0,$nMax=0)
	  {
		  $this->min=$nMin;
		  $this->max=$nMax;
	  }
	  
	  function SetUnitsLabel($cLabel)
	  {
		  $this->unitsLabel=$cLabel;
	  }
	  
	  function JSGauge($cDOMID)
	  {
		  $this->cDOMID=$cDOMID;
		  $this->value=0;
		  $this->cLabel='';
		  $this->value=0;
		  $this->min=0;
		  $this->max=0;
		  $this->majorTicks=8;
		  $this->minorTicks=5;
		  $this->majorTickLabel='true';
		  $this->greenFrom=0;
		  $this->greenTo=0;
		  $this->yellowFrom=0;
		  $this->yellowTo=0;
		  $this->redFrom=0;
		  $this->redTo=0;
		  $this->unitsLabel='';
	  }
	  
	  function flush()
	  {
		  flush();
	  }
	  
	  function post()
	  {
		  ?>
		  <script type="text/javascript">
		  	// Created By class.JSGauge
		  	$("<?php echo $this->cDOMID;?>").gauge({
				label: '<?php echo $this->cLabel;?>',
				unitsLabel: '<?php echo $this->unitsLabel;?>',
				value: <?php echo $this->value;?>,
				min: <?php echo $this->min;?>,
				max: <?php echo $this->max;?>,
				majorTicks: <?php echo $this->majorTicks;?>,
				minorTicks: <?php echo $this->minorTicks;?>,
				majorTickLabel: <?php echo $this->majorTickLabel;?>,
				greenFrom: <?php echo $this->greenFrom;?>,
				greenTo: <?php echo $this->greenTo;?>,
				yellowFrom: <?php echo $this->yellowFrom;?>,
				yellowTo: <?php echo $this->yellowTo;?>,
				redFrom: <?php echo $this->redFrom;?>,
				redTo:  <?php echo $this->redTo;?>,
				});	
		  </script>
		  <?php
	  }
	  function draw()
	  {
	  	  ?>
		  <script type="text/javascript">
		  $(document).ready(function()
		  {
		  	// Generated By class.JSGauge
	  	  	$("<?php echo $this->cDOMID;?>").gauge('draw');
		  });
		  </script>
		  <?php
		  $this->flush();
	  }
  }
/*
				$("<?php echo $aJSInnards['DOM_ID'];?>").gauge({
				label: '<?php echo $aJSInnards['label'];?>',
				value: <?php echo $aJSInnards['value'];?>,
				min: <?php echo $aJSInnards['min'];?>,
				max: <?php echo $aJSInnards['max'];?>,
				majorTicks: 8,
				minorTicks: 5, 
				majorTickLabel: true,  	
				greenFrom: <?php echo $aJSInnards['greenFrom'];?>,
				greenTo: <?php echo $aJSInnards['greenTo'];?>,
				yellowFrom: <?php echo $aJSInnards['yellowFrom'];?>,
				yellowTo: <?php echo $aJSInnards['yellowTo'];?>,
				redFrom: <?php echo $aJSInnards['redFrom'];?>,
				redTo:  <?php echo $aJSInnards['redTo'];?>, 
				});	
				$("<?php echo $aJSInnards['DOM_ID'];?>").gauge("draw");	
			<?php
			echo '</script>'.LF;
*/